name: flutter_project
description: "Front-end-part"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.1
  http: ^1.0.0
  flutter_localizations: # 添加 Flutter 本地化支持
    sdk: flutter
  intl: ^0.19.0 # 添加 intl 进行本地化
  flutter_gen: ^5.10.0
  shared_preferences: ^2.2.2  # 确保是最新版本



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/temp_data/mock_login_data.json
    - assets/images/孩子-哈！.png
    - assets/images/烧杯.png
    - assets/images/background/实验室-试剂选择场景-低饱和无氛围处理版.png
    - assets/images/background/实验室-器材组装场景.png
